CREATE TABLE ITEM(
	ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
	ITEM_NAME VARCHAR(16) ,
	ITEM_COST CHAR(4) ,
	ITEM_CALORIES CHAR(6),
	ID BIGINT 
	

);

CREATE TABLE MEAL(
	
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	MEAL_NAME VARCHAR(64) NOT NULL,
	MARKET_COST CHAR(4) NOT NULL,
	OVERALL_COST CHAR(4) NOT NULL,
	MEAL_CALORIES CHAR(6) NOT NULL
	
	

);
ALTER TABLE ITEM 
	ADD FOREIGN KEY(ID) 
	REFERENCES MEAL(ID)